repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.4.0
    hooks:
      - id: go-fmt
      - id: go-vet
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/koalaman/shellcheck-pre-commit
    rev: v0.10.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/dnephin/pre-commit-mix-format
    rev: v1.0.0
    hooks:
      - id: mix-format