version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: aerouser
      POSTGRES_PASSWORD: aeropass
      POSTGRES_DB: aerophoenix_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  nats:
    image: nats:2.9.4
    ports:
      - "4222:4222"
      - "8222:8222"

  flyd-sim:
    build:
      context: ../apps/flyd-sim
      dockerfile: Dockerfile
    environment:
      - NATS_URL=nats://nats:4222
    volumes:
      - ../apps/flyd-sim/data:/data
    ports:
      - "50051:50051"
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - postgres
      - nats

  net-sim:
    build:
      context: ../apps/net-sim
    environment:
      - FLYD_SIM_BASE=http://flyd-sim:8080
    ports:
      - "7070:7070"
    depends_on:
      - flyd-sim

  prometheus:
    image: prom/prometheus:v2.44.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/rules:/etc/prometheus/rules
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.0.0
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  postgres_data: