{
 "title": "AeroPhoenix Overview",
 "panels": [
  {
   "title": "Phoenix Endpoint Duration (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "phoenix_endpoint_stop_duration_sum / phoenix_endpoint_stop_duration_count * 1000"
    }
   ]
  },
  {
   "title": "UI Actions (total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(aerophoenix_ui_actions_count)"
    }
   ]
  },
  {
   "title": "Machine Updates/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "rate(aerophoenix_machines_updates[1m])"
    }
   ]
  }
 ]
}