// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/machine.proto

package machine

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MigrationStrategy int32

const (
	MigrationStrategy_STOP_AND_MOVE      MigrationStrategy = 0 // Stop source, move state, start target
	MigrationStrategy_LIVE_MIGRATION     MigrationStrategy = 1 // Keep running during transfer (future)
	MigrationStrategy_CLONE_AND_REDIRECT MigrationStrategy = 2 // Create clone, redirect traffic, destroy source
)

// Enum value maps for MigrationStrategy.
var (
	MigrationStrategy_name = map[int32]string{
		0: "STOP_AND_MOVE",
		1: "LIVE_MIGRATION",
		2: "CLONE_AND_REDIRECT",
	}
	MigrationStrategy_value = map[string]int32{
		"STOP_AND_MOVE":      0,
		"LIVE_MIGRATION":     1,
		"CLONE_AND_REDIRECT": 2,
	}
)

func (x MigrationStrategy) Enum() *MigrationStrategy {
	p := new(MigrationStrategy)
	*p = x
	return p
}

func (x MigrationStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MigrationStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_machine_proto_enumTypes[0].Descriptor()
}

func (MigrationStrategy) Type() protoreflect.EnumType {
	return &file_proto_machine_proto_enumTypes[0]
}

func (x MigrationStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MigrationStrategy.Descriptor instead.
func (MigrationStrategy) EnumDescriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{0}
}

type MigrationPhase int32

const (
	MigrationPhase_PHASE_UNKNOWN            MigrationPhase = 0
	MigrationPhase_PHASE_VALIDATING         MigrationPhase = 1
	MigrationPhase_PHASE_PREPARING_SOURCE   MigrationPhase = 2
	MigrationPhase_PHASE_CREATING_TARGET    MigrationPhase = 3
	MigrationPhase_PHASE_TRANSFERRING_STATE MigrationPhase = 4
	MigrationPhase_PHASE_VERIFYING_STATE    MigrationPhase = 5
	MigrationPhase_PHASE_NETWORK_CUTOVER    MigrationPhase = 6
	MigrationPhase_PHASE_CLEANUP            MigrationPhase = 7
	MigrationPhase_PHASE_COMPLETED          MigrationPhase = 8
	MigrationPhase_PHASE_FAILED             MigrationPhase = 9
	MigrationPhase_PHASE_ROLLING_BACK       MigrationPhase = 10
)

// Enum value maps for MigrationPhase.
var (
	MigrationPhase_name = map[int32]string{
		0:  "PHASE_UNKNOWN",
		1:  "PHASE_VALIDATING",
		2:  "PHASE_PREPARING_SOURCE",
		3:  "PHASE_CREATING_TARGET",
		4:  "PHASE_TRANSFERRING_STATE",
		5:  "PHASE_VERIFYING_STATE",
		6:  "PHASE_NETWORK_CUTOVER",
		7:  "PHASE_CLEANUP",
		8:  "PHASE_COMPLETED",
		9:  "PHASE_FAILED",
		10: "PHASE_ROLLING_BACK",
	}
	MigrationPhase_value = map[string]int32{
		"PHASE_UNKNOWN":            0,
		"PHASE_VALIDATING":         1,
		"PHASE_PREPARING_SOURCE":   2,
		"PHASE_CREATING_TARGET":    3,
		"PHASE_TRANSFERRING_STATE": 4,
		"PHASE_VERIFYING_STATE":    5,
		"PHASE_NETWORK_CUTOVER":    6,
		"PHASE_CLEANUP":            7,
		"PHASE_COMPLETED":          8,
		"PHASE_FAILED":             9,
		"PHASE_ROLLING_BACK":       10,
	}
)

func (x MigrationPhase) Enum() *MigrationPhase {
	p := new(MigrationPhase)
	*p = x
	return p
}

func (x MigrationPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MigrationPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_machine_proto_enumTypes[1].Descriptor()
}

func (MigrationPhase) Type() protoreflect.EnumType {
	return &file_proto_machine_proto_enumTypes[1]
}

func (x MigrationPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MigrationPhase.Descriptor instead.
func (MigrationPhase) EnumDescriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{1}
}

type MigrationState int32

const (
	MigrationState_STATE_PENDING     MigrationState = 0
	MigrationState_STATE_IN_PROGRESS MigrationState = 1
	MigrationState_STATE_COMPLETED   MigrationState = 2
	MigrationState_STATE_FAILED      MigrationState = 3
	MigrationState_STATE_ROLLED_BACK MigrationState = 4
)

// Enum value maps for MigrationState.
var (
	MigrationState_name = map[int32]string{
		0: "STATE_PENDING",
		1: "STATE_IN_PROGRESS",
		2: "STATE_COMPLETED",
		3: "STATE_FAILED",
		4: "STATE_ROLLED_BACK",
	}
	MigrationState_value = map[string]int32{
		"STATE_PENDING":     0,
		"STATE_IN_PROGRESS": 1,
		"STATE_COMPLETED":   2,
		"STATE_FAILED":      3,
		"STATE_ROLLED_BACK": 4,
	}
)

func (x MigrationState) Enum() *MigrationState {
	p := new(MigrationState)
	*p = x
	return p
}

func (x MigrationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MigrationState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_machine_proto_enumTypes[2].Descriptor()
}

func (MigrationState) Type() protoreflect.EnumType {
	return &file_proto_machine_proto_enumTypes[2]
}

func (x MigrationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MigrationState.Descriptor instead.
func (MigrationState) EnumDescriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{2}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_machine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_machine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_proto_machine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_proto_machine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{3}
}

func (x *CreateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_machine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_machine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{5}
}

func (x *GetResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type ActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_proto_machine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{6}
}

func (x *ActionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_proto_machine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{7}
}

func (x *ActionResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// Migration request with comprehensive configuration
type MigrateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	TargetRegion  string                 `protobuf:"bytes,2,opt,name=target_region,json=targetRegion,proto3" json:"target_region,omitempty"`
	Strategy      MigrationStrategy      `protobuf:"varint,3,opt,name=strategy,proto3,enum=aerophoenix.machine.MigrationStrategy" json:"strategy,omitempty"`
	Options       *MigrationOptions      `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateRequest) Reset() {
	*x = MigrateRequest{}
	mi := &file_proto_machine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateRequest) ProtoMessage() {}

func (x *MigrateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateRequest.ProtoReflect.Descriptor instead.
func (*MigrateRequest) Descriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{8}
}

func (x *MigrateRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *MigrateRequest) GetTargetRegion() string {
	if x != nil {
		return x.TargetRegion
	}
	return ""
}

func (x *MigrateRequest) GetStrategy() MigrationStrategy {
	if x != nil {
		return x.Strategy
	}
	return MigrationStrategy_STOP_AND_MOVE
}

func (x *MigrateRequest) GetOptions() *MigrationOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type MigrationOptions struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TimeoutSeconds        int64                  `protobuf:"varint,1,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`                                        // Max time for migration
	PreserveIp            bool                   `protobuf:"varint,2,opt,name=preserve_ip,json=preserveIp,proto3" json:"preserve_ip,omitempty"`                                                    // Attempt to preserve anycast IP
	SkipStateVerification bool                   `protobuf:"varint,3,opt,name=skip_state_verification,json=skipStateVerification,proto3" json:"skip_state_verification,omitempty"`                 // Skip checksum validation (faster but risky)
	Metadata              map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional migration metadata
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MigrationOptions) Reset() {
	*x = MigrationOptions{}
	mi := &file_proto_machine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationOptions) ProtoMessage() {}

func (x *MigrationOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationOptions.ProtoReflect.Descriptor instead.
func (*MigrationOptions) Descriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{9}
}

func (x *MigrationOptions) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *MigrationOptions) GetPreserveIp() bool {
	if x != nil {
		return x.PreserveIp
	}
	return false
}

func (x *MigrationOptions) GetSkipStateVerification() bool {
	if x != nil {
		return x.SkipStateVerification
	}
	return false
}

func (x *MigrationOptions) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MigrateResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MigrationId         string                 `protobuf:"bytes,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
	CurrentPhase        MigrationPhase         `protobuf:"varint,2,opt,name=current_phase,json=currentPhase,proto3,enum=aerophoenix.machine.MigrationPhase" json:"current_phase,omitempty"`
	Message             string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	EstimatedDurationMs int64                  `protobuf:"varint,4,opt,name=estimated_duration_ms,json=estimatedDurationMs,proto3" json:"estimated_duration_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MigrateResponse) Reset() {
	*x = MigrateResponse{}
	mi := &file_proto_machine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateResponse) ProtoMessage() {}

func (x *MigrateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateResponse.ProtoReflect.Descriptor instead.
func (*MigrateResponse) Descriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{10}
}

func (x *MigrateResponse) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

func (x *MigrateResponse) GetCurrentPhase() MigrationPhase {
	if x != nil {
		return x.CurrentPhase
	}
	return MigrationPhase_PHASE_UNKNOWN
}

func (x *MigrateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MigrateResponse) GetEstimatedDurationMs() int64 {
	if x != nil {
		return x.EstimatedDurationMs
	}
	return 0
}

type MigrationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MigrationId   string                 `protobuf:"bytes,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationStatusRequest) Reset() {
	*x = MigrationStatusRequest{}
	mi := &file_proto_machine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationStatusRequest) ProtoMessage() {}

func (x *MigrationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationStatusRequest.ProtoReflect.Descriptor instead.
func (*MigrationStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{11}
}

func (x *MigrationStatusRequest) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

type MigrationStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MigrationId      string                 `protobuf:"bytes,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
	Phase            MigrationPhase         `protobuf:"varint,2,opt,name=phase,proto3,enum=aerophoenix.machine.MigrationPhase" json:"phase,omitempty"`
	State            MigrationState         `protobuf:"varint,3,opt,name=state,proto3,enum=aerophoenix.machine.MigrationState" json:"state,omitempty"`
	SourceRegion     string                 `protobuf:"bytes,4,opt,name=source_region,json=sourceRegion,proto3" json:"source_region,omitempty"`
	TargetRegion     string                 `protobuf:"bytes,5,opt,name=target_region,json=targetRegion,proto3" json:"target_region,omitempty"`
	BytesTransferred int64                  `protobuf:"varint,6,opt,name=bytes_transferred,json=bytesTransferred,proto3" json:"bytes_transferred,omitempty"`
	TotalBytes       int64                  `protobuf:"varint,7,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	Steps            []*MigrationStepStatus `protobuf:"bytes,8,rep,name=steps,proto3" json:"steps,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StartedAt        int64                  `protobuf:"varint,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt      int64                  `protobuf:"varint,11,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MigrationStatusResponse) Reset() {
	*x = MigrationStatusResponse{}
	mi := &file_proto_machine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationStatusResponse) ProtoMessage() {}

func (x *MigrationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationStatusResponse.ProtoReflect.Descriptor instead.
func (*MigrationStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{12}
}

func (x *MigrationStatusResponse) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

func (x *MigrationStatusResponse) GetPhase() MigrationPhase {
	if x != nil {
		return x.Phase
	}
	return MigrationPhase_PHASE_UNKNOWN
}

func (x *MigrationStatusResponse) GetState() MigrationState {
	if x != nil {
		return x.State
	}
	return MigrationState_STATE_PENDING
}

func (x *MigrationStatusResponse) GetSourceRegion() string {
	if x != nil {
		return x.SourceRegion
	}
	return ""
}

func (x *MigrationStatusResponse) GetTargetRegion() string {
	if x != nil {
		return x.TargetRegion
	}
	return ""
}

func (x *MigrationStatusResponse) GetBytesTransferred() int64 {
	if x != nil {
		return x.BytesTransferred
	}
	return 0
}

func (x *MigrationStatusResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *MigrationStatusResponse) GetSteps() []*MigrationStepStatus {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *MigrationStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *MigrationStatusResponse) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *MigrationStatusResponse) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

type MigrationStepStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepName      string                 `protobuf:"bytes,1,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	Completed     bool                   `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	DurationMs    int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationStepStatus) Reset() {
	*x = MigrationStepStatus{}
	mi := &file_proto_machine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationStepStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationStepStatus) ProtoMessage() {}

func (x *MigrationStepStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationStepStatus.ProtoReflect.Descriptor instead.
func (*MigrationStepStatus) Descriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{13}
}

func (x *MigrationStepStatus) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *MigrationStepStatus) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *MigrationStepStatus) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *MigrationStepStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MigrationProgressEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MigrationId     string                 `protobuf:"bytes,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
	Phase           MigrationPhase         `protobuf:"varint,2,opt,name=phase,proto3,enum=aerophoenix.machine.MigrationPhase" json:"phase,omitempty"`
	ProgressPercent int32                  `protobuf:"varint,3,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	Message         string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp       int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MigrationProgressEvent) Reset() {
	*x = MigrationProgressEvent{}
	mi := &file_proto_machine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationProgressEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationProgressEvent) ProtoMessage() {}

func (x *MigrationProgressEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationProgressEvent.ProtoReflect.Descriptor instead.
func (*MigrationProgressEvent) Descriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{14}
}

func (x *MigrationProgressEvent) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

func (x *MigrationProgressEvent) GetPhase() MigrationPhase {
	if x != nil {
		return x.Phase
	}
	return MigrationPhase_PHASE_UNKNOWN
}

func (x *MigrationProgressEvent) GetProgressPercent() int32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *MigrationProgressEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MigrationProgressEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_machine_proto protoreflect.FileDescriptor

const file_proto_machine_proto_rawDesc = "" +
	"\n" +
	"\x13proto/machine.proto\x12\x13aerophoenix.machine\"\r\n" +
	"\vPingRequest\" \n" +
	"\fPingResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\";\n" +
	"\rCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\"8\n" +
	"\x0eCreateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"M\n" +
	"\vGetResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\"\x1f\n" +
	"\rActionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\x0eActionResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"\xd9\x01\n" +
	"\x0eMigrateRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12#\n" +
	"\rtarget_region\x18\x02 \x01(\tR\ftargetRegion\x12B\n" +
	"\bstrategy\x18\x03 \x01(\x0e2&.aerophoenix.machine.MigrationStrategyR\bstrategy\x12?\n" +
	"\aoptions\x18\x04 \x01(\v2%.aerophoenix.machine.MigrationOptionsR\aoptions\"\xa2\x02\n" +
	"\x10MigrationOptions\x12'\n" +
	"\x0ftimeout_seconds\x18\x01 \x01(\x03R\x0etimeoutSeconds\x12\x1f\n" +
	"\vpreserve_ip\x18\x02 \x01(\bR\n" +
	"preserveIp\x126\n" +
	"\x17skip_state_verification\x18\x03 \x01(\bR\x15skipStateVerification\x12O\n" +
	"\bmetadata\x18\x04 \x03(\v23.aerophoenix.machine.MigrationOptions.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcc\x01\n" +
	"\x0fMigrateResponse\x12!\n" +
	"\fmigration_id\x18\x01 \x01(\tR\vmigrationId\x12H\n" +
	"\rcurrent_phase\x18\x02 \x01(\x0e2#.aerophoenix.machine.MigrationPhaseR\fcurrentPhase\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x122\n" +
	"\x15estimated_duration_ms\x18\x04 \x01(\x03R\x13estimatedDurationMs\";\n" +
	"\x16MigrationStatusRequest\x12!\n" +
	"\fmigration_id\x18\x01 \x01(\tR\vmigrationId\"\xf1\x03\n" +
	"\x17MigrationStatusResponse\x12!\n" +
	"\fmigration_id\x18\x01 \x01(\tR\vmigrationId\x129\n" +
	"\x05phase\x18\x02 \x01(\x0e2#.aerophoenix.machine.MigrationPhaseR\x05phase\x129\n" +
	"\x05state\x18\x03 \x01(\x0e2#.aerophoenix.machine.MigrationStateR\x05state\x12#\n" +
	"\rsource_region\x18\x04 \x01(\tR\fsourceRegion\x12#\n" +
	"\rtarget_region\x18\x05 \x01(\tR\ftargetRegion\x12+\n" +
	"\x11bytes_transferred\x18\x06 \x01(\x03R\x10bytesTransferred\x12\x1f\n" +
	"\vtotal_bytes\x18\a \x01(\x03R\n" +
	"totalBytes\x12>\n" +
	"\x05steps\x18\b \x03(\v2(.aerophoenix.machine.MigrationStepStatusR\x05steps\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\v \x01(\x03R\vcompletedAt\"\x87\x01\n" +
	"\x13MigrationStepStatus\x12\x1b\n" +
	"\tstep_name\x18\x01 \x01(\tR\bstepName\x12\x1c\n" +
	"\tcompleted\x18\x02 \x01(\bR\tcompleted\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xd9\x01\n" +
	"\x16MigrationProgressEvent\x12!\n" +
	"\fmigration_id\x18\x01 \x01(\tR\vmigrationId\x129\n" +
	"\x05phase\x18\x02 \x01(\x0e2#.aerophoenix.machine.MigrationPhaseR\x05phase\x12)\n" +
	"\x10progress_percent\x18\x03 \x01(\x05R\x0fprogressPercent\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp*R\n" +
	"\x11MigrationStrategy\x12\x11\n" +
	"\rSTOP_AND_MOVE\x10\x00\x12\x12\n" +
	"\x0eLIVE_MIGRATION\x10\x01\x12\x16\n" +
	"\x12CLONE_AND_REDIRECT\x10\x02*\x96\x02\n" +
	"\x0eMigrationPhase\x12\x11\n" +
	"\rPHASE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10PHASE_VALIDATING\x10\x01\x12\x1a\n" +
	"\x16PHASE_PREPARING_SOURCE\x10\x02\x12\x19\n" +
	"\x15PHASE_CREATING_TARGET\x10\x03\x12\x1c\n" +
	"\x18PHASE_TRANSFERRING_STATE\x10\x04\x12\x19\n" +
	"\x15PHASE_VERIFYING_STATE\x10\x05\x12\x19\n" +
	"\x15PHASE_NETWORK_CUTOVER\x10\x06\x12\x11\n" +
	"\rPHASE_CLEANUP\x10\a\x12\x13\n" +
	"\x0fPHASE_COMPLETED\x10\b\x12\x10\n" +
	"\fPHASE_FAILED\x10\t\x12\x16\n" +
	"\x12PHASE_ROLLING_BACK\x10\n" +
	"*x\n" +
	"\x0eMigrationState\x12\x11\n" +
	"\rSTATE_PENDING\x10\x00\x12\x15\n" +
	"\x11STATE_IN_PROGRESS\x10\x01\x12\x13\n" +
	"\x0fSTATE_COMPLETED\x10\x02\x12\x10\n" +
	"\fSTATE_FAILED\x10\x03\x12\x15\n" +
	"\x11STATE_ROLLED_BACK\x10\x042\xfe\x05\n" +
	"\x0eMachineService\x12K\n" +
	"\x04Ping\x12 .aerophoenix.machine.PingRequest\x1a!.aerophoenix.machine.PingResponse\x12X\n" +
	"\rCreateMachine\x12\".aerophoenix.machine.CreateRequest\x1a#.aerophoenix.machine.CreateResponse\x12O\n" +
	"\n" +
	"GetMachine\x12\x1f.aerophoenix.machine.GetRequest\x1a .aerophoenix.machine.GetResponse\x12W\n" +
	"\fStartMachine\x12\".aerophoenix.machine.ActionRequest\x1a#.aerophoenix.machine.ActionResponse\x12V\n" +
	"\vStopMachine\x12\".aerophoenix.machine.ActionRequest\x1a#.aerophoenix.machine.ActionResponse\x12[\n" +
	"\x0eMigrateMachine\x12#.aerophoenix.machine.MigrateRequest\x1a$.aerophoenix.machine.MigrateResponse\x12o\n" +
	"\x12GetMigrationStatus\x12+.aerophoenix.machine.MigrationStatusRequest\x1a,.aerophoenix.machine.MigrationStatusResponse\x12u\n" +
	"\x17StreamMigrationProgress\x12+.aerophoenix.machine.MigrationStatusRequest\x1a+.aerophoenix.machine.MigrationProgressEvent0\x01BAZ?github.com/devghori1264/aerophoenix/apps/flyd-sim/proto;machineb\x06proto3"

var (
	file_proto_machine_proto_rawDescOnce sync.Once
	file_proto_machine_proto_rawDescData []byte
)

func file_proto_machine_proto_rawDescGZIP() []byte {
	file_proto_machine_proto_rawDescOnce.Do(func() {
		file_proto_machine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_machine_proto_rawDesc), len(file_proto_machine_proto_rawDesc)))
	})
	return file_proto_machine_proto_rawDescData
}

var file_proto_machine_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_machine_proto_goTypes = []any{
	(MigrationStrategy)(0),          // 0: aerophoenix.machine.MigrationStrategy
	(MigrationPhase)(0),             // 1: aerophoenix.machine.MigrationPhase
	(MigrationState)(0),             // 2: aerophoenix.machine.MigrationState
	(*PingRequest)(nil),             // 3: aerophoenix.machine.PingRequest
	(*PingResponse)(nil),            // 4: aerophoenix.machine.PingResponse
	(*CreateRequest)(nil),           // 5: aerophoenix.machine.CreateRequest
	(*CreateResponse)(nil),          // 6: aerophoenix.machine.CreateResponse
	(*GetRequest)(nil),              // 7: aerophoenix.machine.GetRequest
	(*GetResponse)(nil),             // 8: aerophoenix.machine.GetResponse
	(*ActionRequest)(nil),           // 9: aerophoenix.machine.ActionRequest
	(*ActionResponse)(nil),          // 10: aerophoenix.machine.ActionResponse
	(*MigrateRequest)(nil),          // 11: aerophoenix.machine.MigrateRequest
	(*MigrationOptions)(nil),        // 12: aerophoenix.machine.MigrationOptions
	(*MigrateResponse)(nil),         // 13: aerophoenix.machine.MigrateResponse
	(*MigrationStatusRequest)(nil),  // 14: aerophoenix.machine.MigrationStatusRequest
	(*MigrationStatusResponse)(nil), // 15: aerophoenix.machine.MigrationStatusResponse
	(*MigrationStepStatus)(nil),     // 16: aerophoenix.machine.MigrationStepStatus
	(*MigrationProgressEvent)(nil),  // 17: aerophoenix.machine.MigrationProgressEvent
	nil,                             // 18: aerophoenix.machine.MigrationOptions.MetadataEntry
}
var file_proto_machine_proto_depIdxs = []int32{
	0,  // 0: aerophoenix.machine.MigrateRequest.strategy:type_name -> aerophoenix.machine.MigrationStrategy
	12, // 1: aerophoenix.machine.MigrateRequest.options:type_name -> aerophoenix.machine.MigrationOptions
	18, // 2: aerophoenix.machine.MigrationOptions.metadata:type_name -> aerophoenix.machine.MigrationOptions.MetadataEntry
	1,  // 3: aerophoenix.machine.MigrateResponse.current_phase:type_name -> aerophoenix.machine.MigrationPhase
	1,  // 4: aerophoenix.machine.MigrationStatusResponse.phase:type_name -> aerophoenix.machine.MigrationPhase
	2,  // 5: aerophoenix.machine.MigrationStatusResponse.state:type_name -> aerophoenix.machine.MigrationState
	16, // 6: aerophoenix.machine.MigrationStatusResponse.steps:type_name -> aerophoenix.machine.MigrationStepStatus
	1,  // 7: aerophoenix.machine.MigrationProgressEvent.phase:type_name -> aerophoenix.machine.MigrationPhase
	3,  // 8: aerophoenix.machine.MachineService.Ping:input_type -> aerophoenix.machine.PingRequest
	5,  // 9: aerophoenix.machine.MachineService.CreateMachine:input_type -> aerophoenix.machine.CreateRequest
	7,  // 10: aerophoenix.machine.MachineService.GetMachine:input_type -> aerophoenix.machine.GetRequest
	9,  // 11: aerophoenix.machine.MachineService.StartMachine:input_type -> aerophoenix.machine.ActionRequest
	9,  // 12: aerophoenix.machine.MachineService.StopMachine:input_type -> aerophoenix.machine.ActionRequest
	11, // 13: aerophoenix.machine.MachineService.MigrateMachine:input_type -> aerophoenix.machine.MigrateRequest
	14, // 14: aerophoenix.machine.MachineService.GetMigrationStatus:input_type -> aerophoenix.machine.MigrationStatusRequest
	14, // 15: aerophoenix.machine.MachineService.StreamMigrationProgress:input_type -> aerophoenix.machine.MigrationStatusRequest
	4,  // 16: aerophoenix.machine.MachineService.Ping:output_type -> aerophoenix.machine.PingResponse
	6,  // 17: aerophoenix.machine.MachineService.CreateMachine:output_type -> aerophoenix.machine.CreateResponse
	8,  // 18: aerophoenix.machine.MachineService.GetMachine:output_type -> aerophoenix.machine.GetResponse
	10, // 19: aerophoenix.machine.MachineService.StartMachine:output_type -> aerophoenix.machine.ActionResponse
	10, // 20: aerophoenix.machine.MachineService.StopMachine:output_type -> aerophoenix.machine.ActionResponse
	13, // 21: aerophoenix.machine.MachineService.MigrateMachine:output_type -> aerophoenix.machine.MigrateResponse
	15, // 22: aerophoenix.machine.MachineService.GetMigrationStatus:output_type -> aerophoenix.machine.MigrationStatusResponse
	17, // 23: aerophoenix.machine.MachineService.StreamMigrationProgress:output_type -> aerophoenix.machine.MigrationProgressEvent
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_machine_proto_init() }
func file_proto_machine_proto_init() {
	if File_proto_machine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_machine_proto_rawDesc), len(file_proto_machine_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_machine_proto_goTypes,
		DependencyIndexes: file_proto_machine_proto_depIdxs,
		EnumInfos:         file_proto_machine_proto_enumTypes,
		MessageInfos:      file_proto_machine_proto_msgTypes,
	}.Build()
	File_proto_machine_proto = out.File
	file_proto_machine_proto_goTypes = nil
	file_proto_machine_proto_depIdxs = nil
}
