name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-elixir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: '1.15'
          otp-version: '25'
      - name: Install deps
        run: |
          cd apps/phoenix_ui
          mix deps.get

  build-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - run: |
          cd apps/flyd-sim
          go test ./...
